### ISSUE TITLE
Help! Error on ionic upload

### ISSUE THREAD

**Issue by gbgelado** [klarsys/angular-material-icons#63]
If I use angular-material-icons: 

buffer.js:825
    throw new TypeError('value is out of bounds');
    ^

TypeError: value is out of bounds
    at checkInt (buffer.js:825:11)
    at Buffer.writeUInt16LE (buffer.js:883:5)
    at /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/node_modules/zip-stream/lib/headers.js:41:32
    at Array.forEach (native)
    at ZipHeaderCentralFooter.ZipHeader.toBuffer (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/node_modules/zip-stream/lib/headers.js:28:15)
    at Object.exports.encode (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/node_modules/zip-stream/lib/headers.js:198:24)
    at ZipStream._writeCentralDirectory (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/node_modules/zip-stream/lib/zip-stream.js:220:22)
    at ZipStream.finalize (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/node_modules/zip-stream/lib/zip-stream.js:270:8)
    at Zip.finalize (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/lib/modules/zip/index.js:39:15)
    at Archiver._onQueueEnd (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/lib/modules/core/index.js:91:26)

**Comment by urmilparikh** [comment]
Hi @gbgelado, please share a codepen or so to demonstrate issue.
